### ISSUE TITLE
The negotiation of encryption algorithm is failed

### ISSUE THREAD

**Issue by scsi050** [Terminals-Origin/Terminals#110]
Getting this error message for any SSH connection I attempt. "The negotiation of encryption algorithm is failed"

Version: 4.0.1.16210
CommandLine: "C:\Program Files (x86)\Terminals\Terminals.exe" 
CurrentDirectory: C:\Program Files (x86)\Terminals
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
ProcessorCount: 4
UserInteractive: True
Framework Version: 4.0.30319.36388
WorkingSet: 82849792
Is 64bit OS: True
Is 64bit Proces: True

```
FATAL 2017-10-16 13:59:00,736 199796ms Terminals              Connect            - Connecting to unknown Connection
Granados.SSHException: The negotiation of encryption algorithm is failed
   at Granados.SSH2.KeyExchanger.DecideCipherAlgorithm(String data)
   at Granados.SSH2.KeyExchanger.ProcessKEXINIT(DataFragment packet)
   at Granados.SSH2.SSH2Connection.Connect()
   at Granados.SSHConnection.ConnectMain(SSHConnectionParameter param, ISSHConnectionEventReceiver receiver, VersionExchangeHandler pnh, AbstractGranadosSocket s)
   at SSHClient.Protocol.Connect(Socket s)
   at Terminals.Connections.TerminalConnection.ConfigureSshConnection(IGuardedSecurity security)
   at Terminals.Connections.TerminalConnection.Connect()
```

**Comment by jirkapok** [comment]
try to use putty to ensure you are able to connect to the machine. If yes, this should be resolved by #46.
