### ISSUE TITLE
Null reference exception when saving generated ssh keys

### ISSUE THREAD

**Issue by FDUdannychen** [Terminals-Origin/Terminals#116]
Windows 10, installed from 4.0,1 MSI.

FATAL 2017-10-20 15:39:17,892 23257ms Terminals              howApplicationExit - System.NullReferenceException: Object reference not set to an instance of an object.
   at SSHClient.Preferences.GenerateSSH2Key()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
FATAL 2017-10-20 15:39:17,892 23257ms Terminals              howApplicationExit - Application has to be terminated.

**Comment by jirkapok** [comment]
Wont fix since development of putty integration is in progress.
