### ISSUE TITLE
Program crashes while trying to export favorites

### ISSUE THREAD

**Issue by Bounz** [Terminals-Origin/Terminals#12]
Hi.
Terminals crashes while trying to export favorites.
I found two cases:
1. Open "File/Export connections" window, press "Select all" - crash.
2. Open "File/Export connections" window, manually select all connections press "Export" - crash.

**Comment by kendoori** [comment]
am having same issue... running Version: 4.0.0.41829 on Windows 10 Professional

**Comment by paulnevlud** [comment]
I'm having the same issue, but the crash occurs when choosing File/Export Connections. Here is the content of my log file. 

INFO  2017-04-18 13:58:26,046   161ms Terminals              Main               - -------------------------------Title: Terminals 4.0.0 started Version:4.0.0.41829 Date:4/1/2017 4:14:19 PM-------------------------------
INFO  2017-04-18 13:58:26,082   197ms Terminals              Main               - Start state 1 Complete: Unhandled exceptions
INFO  2017-04-18 13:58:26,084   199ms Terminals              gGeneralProperties - CommandLine:"C:\Program Files (x86)\Terminals\Terminals.exe" 
INFO  2017-04-18 13:58:26,084   199ms Terminals              gGeneralProperties - CurrentDirectory:C:\Program Files (x86)\Terminals
INFO  2017-04-18 13:58:26,084   199ms Terminals              gGeneralProperties - MachineName:W7CALVSE0GNA3AL
INFO  2017-04-18 13:58:26,085   200ms Terminals              gGeneralProperties - OSVersion:Microsoft Windows NT 6.1.7601 Service Pack 1
INFO  2017-04-18 13:58:26,085   200ms Terminals              gGeneralProperties - ProcessorCount:8
INFO  2017-04-18 13:58:26,086   201ms Terminals              gGeneralProperties - UserInteractive:True
INFO  2017-04-18 13:58:26,086   201ms Terminals              gGeneralProperties - Version:4.0.30319.42000
INFO  2017-04-18 13:58:26,087   202ms Terminals              gGeneralProperties - WorkingSet:24358912
INFO  2017-04-18 13:58:26,088   203ms Terminals              gGeneralProperties - Is64BitOperatingSystem:True
INFO  2017-04-18 13:58:26,088   203ms Terminals              gGeneralProperties - Is64BitProcess:True
INFO  2017-04-18 13:58:26,088   203ms Terminals              Main               - Start state 2 Complete: Log General properties
INFO  2017-04-18 13:58:26,090   205ms Terminals              Main               - Start state 3 Complete: Set application properties
INFO  2017-04-18 13:58:26,124   239ms Terminals              Main               - Start state 4 Complete: Parse command line
INFO  2017-04-18 13:58:26,126   241ms Terminals              Main               - Start state 5 Complete: User account control
INFO  2017-04-18 13:58:26,127   242ms Terminals              Main               - Start state 6 Complete: Set Single instance mode
INFO  2017-04-18 13:58:26,195   310ms Terminals              Main               - Start state 7 Complete: Initilizing Persistence
INFO  2017-04-18 13:58:26,196   311ms Terminals              Main               - Start state 8 Complete: Configuration upgrade
INFO  2017-04-18 13:58:26,197   312ms Terminals              TryLoadFile        - Loading History from: C:\Users\sesa57261\AppData\Local\Robert_Chartier\Terminals\Data\History.xml
FATAL 2017-04-18 14:01:54,686 208800ms Terminals              howApplicationExit - System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminals.Forms.Controls.FavoriteTreeNode.UpdateByFavorite(IFavorite favorite, String toolTip)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNode(IFavorite favorite, Int32 index)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNodes(IEnumerable`1 favorites)
   at Terminals.Forms.ExportForm..ctor(IPersistence persistence, ConnectionManager connectionManager, FavoriteIcons favoriteIcons)
   at Terminals.MainForm.ExportConnectionsListToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
FATAL 2017-04-18 14:01:54,694 208808ms Terminals              howApplicationExit - Application has to be terminated.

**Comment by jirkapok** [comment]
duplicates #1
