### ISSUE TITLE
Terminals 4.0 expects the wrong SSHCLient DLL version

### ISSUE THREAD

**Issue by RossPatterson** [Terminals-Origin/Terminals#13]
I just upgraded from 3.6.1 to 4.0.0, and SSH connections are failing.  The log shows an exception trying to load version 1.0.5230.22543 of the SSHClient DLL, but the version distributed with 4.0.0 is 1.0.6300.41284:

```FATAL 2017-04-18 13:17:01,252 27851ms Terminals              Connect            - Connecting to unknown Connection
System.Configuration.ConfigurationErrorsException: An error occurred creating the configuration section handler for SSH: Could not load file or assembly 'SSHClient, Version=1.0.5230.22543, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. (C:\Users\ropatter\AppData\Local\Robert_Chartier\Terminals\Data\Terminals.config) ---> System.IO.FileNotFoundException: Could not load file or assembly 'SSHClient, Version=1.0.5230.22543, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at System.Configuration.TypeUtil.GetTypeWithReflectionPermission(IInternalConfigHost host, String typeString, Boolean throwOnError)
   at System.Configuration.MgmtConfigurationRecord.CreateSectionFactory(FactoryRecord factoryRecord)
   at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere)
   --- End of inner exception stack trace ---
   at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.ConfigurationSectionCollection.Get(String name)
   at Terminals.Configuration.Settings.get_SSHKeys()
   at Terminals.Connections.TerminalConnection.ConfigureSshConnection(IGuardedSecurity security)
   at Terminals.Connections.TerminalConnection.Connect()
```

**Comment by jhonny-oliveira** [comment]
Same issue here.

**Comment by RossPatterson** [comment]
Decoding those two SSHClient version numbers _a la_ `VersionParser` says the 4.0.0 Terminals build expects a copy of SSHClient.dll compiled at 2017-04-01T22:56:08 (timezone unknown), and is shipping with a version compiled at 2014-04-27T12:31:26.  Since SSHClient is part of the Terminals source tree, it would appear that there was a build error in creating the 4.0.0 package on or about April 1st (depending on where the build was executed).

Either this issue will be automagically fixed in the next published build, or the process itself is broken.  I haven't seen anything checked into the source tree since that date that changes the build process.

**Comment by int03** [comment]
delete configuration reference from Terminals.config.

**Comment by RossPatterson** [comment]
@int03 That did the job!  I editted C:\users\[userid]\AppData\Local\Robert_Chartier\Terminals\Data\Terminasl.config and removed the "SSH" line from:

```
<configSections>
    <section name="FormsSection" type="Terminals.FormsSection, Terminals, Version=3.5.0.22546, Culture=neutral, PublicKeyToken=null" />
    <section name="SSH" type="SSHClient.KeysSection, SSHClient, Version=1.0.5230.22543, Culture=neutral, PublicKeyToken=null" />
    <section name="settings" type="Terminals.TerminalsConfigurationSection, Terminals"/>
</configSections>
```

Thanks!

**Comment by eskes1** [comment]
Version 4.01 is not fixed.

**Comment by Pafzedog** [comment]
> delete configuration reference from Terminals.config.

That is not working for me .
