### ISSUE TITLE
"Terminals has encountered a problem and needs to close" after "File | Export connections" and "Select all"

### ISSUE THREAD

**Issue by emmanueltriballier** [Terminals-Origin/Terminals#14]
I've just installed 4.0.0 version, and when i use "Select all" in "File | Export connections", i have the following error : "Terminals has encountered a problem and needs to close"

**Comment by giwleb** [comment]
I can confirm this behavior

**Comment by giwleb** [comment]
When running as a non-admin:

`ERROR 2017-04-26 09:16:57,412  5483ms Terminals              Register           - Error accessing registry
System.UnauthorizedAccessException: Access to the registry key 'HKEY_CLASSES_ROOT\TRM' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at Terminals.ProtocolHandler.CreateTrmRegistrySubKey()
   at Terminals.ProtocolHandler.Register()
FATAL 2017-04-26 09:17:18,569 26640ms Terminals              howApplicationExit - System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminals.Forms.Controls.FavoriteTreeNode.UpdateByFavorite(IFavorite favorite, String toolTip)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNode(IFavorite favorite, Int32 index)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNodes(IEnumerable`1 favorites)
   at Terminals.Forms.Controls.FavoriteTreeListLoader.OnTreeViewExpand(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterExpand(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnExpanded(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by giwleb** [comment]
When running as an admin:

`INFO  2017-04-26 09:38:55,749   249ms Terminals              TryLoadFile        - Loading History from: C:\Users\olmsu1e9\AppData\Local\Robert_Chartier\Terminals\Data\History.xml
FATAL 2017-04-26 09:40:03,732 68232ms Terminals              howApplicationExit - System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminals.Forms.Controls.FavoriteTreeNode.UpdateByFavorite(IFavorite favorite, String toolTip)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNode(IFavorite favorite, Int32 index)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNodes(IEnumerable1 favorites)
   at Terminals.Forms.Controls.FavoriteTreeListLoader.OnTreeViewExpand(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterExpand(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnExpanded(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
FATAL 2017-04-26 09:40:03,734 68234ms Terminals              howApplicationExit - Application has to be terminated.`

**Comment by alexitosrv** [comment]
I see the same in my log, and I also observe how the app closes itself when trying to export connections.


ERROR 2017-04-28 08:28:59,944  1573ms Terminals              Register           - Error accessing registry
System.UnauthorizedAccessException: Access to the registry key 'HKEY_CLASSES_ROOT\TRM' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey, RegistryKeyPermissionCheck permissionCheck)
   at Terminals.ProtocolHandler.CreateTrmRegistrySubKey()
   at Terminals.ProtocolHandler.Register()

**Comment by KaylaAdmin** [comment]
Are you all running a non admin account on Windows 10 or Windows Server 2016? Is this behaviour seen across different types of accounts and Operating System versions?

**Comment by giwleb** [comment]
For me, the registry error happens when I run as non-admin on Windows 10.

When I run as an admin, I get the second error I posted above.

**Comment by alexitosrv** [comment]
My reported error is generated from Windows 7 64bit

**Comment by mettix** [comment]
Export issue error on Windows 10, as admin and non-admin.

**Comment by jirkapok** [comment]
See also #1 , fix will be delivered with next release.

**Comment by jirkapok** [comment]
Duplicates #1.

**Comment by PorkyProgs** [comment]
I also had this problem. The problem boiled down to that I installed Terminals using an Administrative account but wanted to run it using my normal user account. When I started it using my user account I had the "Terminals has encountered a problem and needs to close" message. When I switched user to the account that installed the application it worked :-), 
Hope this helps,

**Comment by KaylaAdmin** [comment]
That's exactly what is was! I use a non admin account to do most things and use my admin account to approve admin actions.

Now my issue is when I try opening Terminals as an admin, terminals opens it up in an admin session that doesn't have access to any of the connections I need to export. Any suggestions?
