### ISSUE TITLE
can not lock toolbar

### ISSUE THREAD

**Issue by sakurayz** [Terminals-Origin/Terminals#151]
When the network is disconnected , The toolbar will changes position. Cannot be locked in the original position

terminals 4.0.1

**Comment by jirkapok** [comment]
Can you provide exacts steps how to reproduce? and log files, if possible.

**Comment by sakurayz** [comment]
Connect to Remote Desktop, then minimize the terminals window, unplug the network cable, and the toolbar position will change to the next line.

log:
INFO  2018-02-06 10:22:57,503   125ms Terminals              Main               - -------------------------------Title: Terminals 4.0.1 started Version:4.0.1.16210 Date:2017/6/24 17:00:22-------------------------------
INFO  2018-02-06 10:22:57,534   156ms Terminals              Main               - Start state 1 Complete: Unhandled exceptions
INFO  2018-02-06 10:22:57,534   156ms Terminals              gGeneralProperties - CommandLine:"C:\Program Files (x86)\Terminals\Terminals.exe" 
INFO  2018-02-06 10:22:57,534   156ms Terminals              gGeneralProperties - CurrentDirectory:C:\Program Files (x86)\Terminals
INFO  2018-02-06 10:22:57,534   156ms Terminals              gGeneralProperties - MachineName:DESKTOP-xxxxxxx
INFO  2018-02-06 10:22:57,534   156ms Terminals              gGeneralProperties - OSVersion:Microsoft Windows NT 6.2.9200.0
INFO  2018-02-06 10:22:57,534   156ms Terminals              gGeneralProperties - ProcessorCount:4
INFO  2018-02-06 10:22:57,534   156ms Terminals              gGeneralProperties - UserInteractive:True
INFO  2018-02-06 10:22:57,534   156ms Terminals              gGeneralProperties - Version:4.0.30319.42000
INFO  2018-02-06 10:22:57,534   156ms Terminals              gGeneralProperties - WorkingSet:24408064
INFO  2018-02-06 10:22:57,534   156ms Terminals              gGeneralProperties - Is64BitOperatingSystem:True
INFO  2018-02-06 10:22:57,534   156ms Terminals              gGeneralProperties - Is64BitProcess:True
INFO  2018-02-06 10:22:57,534   156ms Terminals              Main               - Start state 2 Complete: Log General properties
INFO  2018-02-06 10:22:57,534   156ms Terminals              Main               - Start state 3 Complete: Set application properties
INFO  2018-02-06 10:22:57,581   203ms Terminals              Main               - Start state 4 Complete: Parse command line
INFO  2018-02-06 10:22:57,581   203ms Terminals              Main               - Start state 5 Complete: User account control
INFO  2018-02-06 10:22:57,581   203ms Terminals              Main               - Start state 6 Complete: Set Single instance mode
INFO  2018-02-06 10:22:57,613   234ms Terminals              Main               - Start state 7 Complete: Initilizing Persistence
INFO  2018-02-06 10:22:57,613   234ms Terminals              Main               - Start state 8 Complete: Configuration upgrade
INFO  2018-02-06 10:22:57,628   250ms Terminals              TryLoadFile        - Loading History from: C:\Users\xxxxx\AppData\Local\Robert_Chartier\Terminals\Data\History.xml
ERROR 2018-02-06 10:23:01,504  4125ms Terminals              Register           - Error accessing registry
System.UnauthorizedAccessException: Access to the registry key 'HKEY_CLASSES_ROOT\TRM' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at Terminals.ProtocolHandler.CreateTrmRegistrySubKey()
   at Terminals.ProtocolHandler.Register()
