### ISSUE TITLE
terminals 4.0.1 ssh crack

### ISSUE THREAD

**Issue by sakurayz** [Terminals-Origin/Terminals#166]
INFO  2018-03-22 09:34:52,310 44033736ms Terminals              Connect            - Connecting to a SSH Connection
FATAL 2018-03-22 09:52:44,572 45105998ms Terminals              howApplicationExit - System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at Granados.IO.PlainSocket.Write(Byte[] data, Int32 offset, Int32 length)
   at Granados.SSH2.SSH2Connection.TransmitPacket(SSH2DataWriter payload)
   at WalburySoftware.TerminalEmulator.DispatchMessage(Object sender, String strText)
   at WalburySoftware.TerminalEmulator.uc_Keyboard.KeyDown(Message KeyMess)
   at WalburySoftware.TerminalEmulator.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
FATAL 2018-03-22 09:52:44,587 45106014ms Terminals              howApplicationExit - Application has to be terminated.

**Comment by jirkapok** [comment]
see #46
