### ISSUE TITLE
Update check to https://api.github.com failing b/c terminals is attempting a connection ustin TLS1.0

### ISSUE THREAD

**Issue by sloanster4000** [Terminals-Origin/Terminals#186]
Logs show: 
ERROR 2018-06-19 13:41:33,884  1303ms Terminals              orPublishedRelease - Failed during Check for release.
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Terminals.Updates.UpdateManager.DownloadReleases()
   at Terminals.Updates.UpdateManager.DownLoadLatestReleaseInfo(Version currentVersion)
   at Terminals.Updates.UpdateManager.TryCheckForPublishedRelease(Version currentVersion)
   at Terminals.Updates.UpdateManager.CheckForPublishedRelease(Version currentVersion)
TCPDUMP show:
TLSv1	61	Alert (Level: Fatal, Description: Protocol Version)
![terminals_update](https://user-images.githubusercontent.com/17884547/41620508-242206ca-73c7-11e8-9f87-8d5b292353e4.png)

**Comment by eran132** [comment]
This appears resolved in the current source. `UpdateManager.DownloadReleases()` now opts the request into TLS 1.2 before contacting GitHub:

```csharp
// Source/Terminals/Updates/UpdateManager.cs
var oldValue = ServicePointManager.SecurityProtocol;
ServicePointManager.SecurityProtocol = oldValue | (SecurityProtocolType)3072; // Tls12
...
var releases = client.DownloadString(Settings.Default.ReleasesUrl);
```

`ReleasesUrl` also points at `https://api.github.com/repos/Terminals-Origin/Terminals/releases`. On any OS where TLS 1.2 is available this resolves the "Could not create SSL/TLS secure channel" failure. Suggest closing.
