### ISSUE TITLE
Terminals Perodically Crashes

### ISSUE THREAD

**Issue by kendoori** [Terminals-Origin/Terminals#196]
I use exclusively for RDP via VPN. The application will periodically just close. Several other members of my team on completely different Windows 10 desktops are getting similar.

Upon last crash, this is what I saw in the logs:

```
FATAL 2018-10-07 13:28:07,602 366548057ms Terminals              howApplicationExit - System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   at Terminals.Connections.ConnectionStateDetector.Stop()
   at Terminals.Connections.RDPConnection.StopReconnect()
   at Terminals.Connections.RDPConnection.CancelReconnect()
   at Terminals.Connections.ConnectionStateDetector.ReconnectionFail()
   at Terminals.Connections.ConnectionStateDetector.TryReconnection(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
FATAL 2018-10-07 13:28:07,608 366548063ms Terminals              howApplicationExit - Application has to be terminated.
```

**Comment by dBradish** [comment]
Happening here as well - but only happens when I'm trying to connect to a server.  After typing in the hostname on the Connect To field, it thinks about it for about 2 seconds then crashes - no error or dialog shown.  I connect to servers probably 60-100 times a day and the crash happens about twice a day - it's just super annoying when I have several other servers open in tabs at the time.

From CurrentLog.txt after my most recent crash a few minutes ago:

INFO  2019-04-10 14:29:13,609 18374303ms Terminals              SaveHistory        - History saved. Duration:11 ms
INFO  2019-04-10 14:29:20,785   138ms Terminals              Main               - -------------------------------Title: Terminals 4.0.1 started Version:4.0.1.16210 Date:6/24/2017 5:00:22 AM-------------------------------
INFO  2019-04-10 14:29:20,822   175ms Terminals              Main               - Start state 1 Complete: Unhandled exceptions
INFO  2019-04-10 14:29:20,824   177ms Terminals              gGeneralProperties - CommandLine:"C:\Program Files (x86)\Terminals\Terminals.exe" 
INFO  2019-04-10 14:29:20,824   177ms Terminals              gGeneralProperties - CurrentDirectory:C:\Program Files (x86)\Terminals
INFO  2019-04-10 14:29:20,825   178ms Terminals              gGeneralProperties - MachineName:<removed>
INFO  2019-04-10 14:29:20,825   178ms Terminals              gGeneralProperties - OSVersion:Microsoft Windows NT 6.2.9200.0
INFO  2019-04-10 14:29:20,825   178ms Terminals              gGeneralProperties - ProcessorCount:8
INFO  2019-04-10 14:29:20,825   178ms Terminals              gGeneralProperties - UserInteractive:True
INFO  2019-04-10 14:29:20,826   179ms Terminals              gGeneralProperties - Version:4.0.30319.42000
INFO  2019-04-10 14:29:20,826   179ms Terminals              gGeneralProperties - WorkingSet:24117248
INFO  2019-04-10 14:29:20,827   180ms Terminals              gGeneralProperties - Is64BitOperatingSystem:True
INFO  2019-04-10 14:29:20,827   180ms Terminals              gGeneralProperties - Is64BitProcess:True
INFO  2019-04-10 14:29:20,827   180ms Terminals              Main               - Start state 2 Complete: Log General properties
INFO  2019-04-10 14:29:20,828   181ms Terminals              Main               - Start state 3 Complete: Set application properties
INFO  2019-04-10 14:29:20,867   220ms Terminals              Main               - Start state 4 Complete: Parse command line
INFO  2019-04-10 14:29:20,869   222ms Terminals              Main               - Start state 5 Complete: User account control
INFO  2019-04-10 14:29:20,869   222ms Terminals              Main               - Start state 6 Complete: Set Single instance mode
INFO  2019-04-10 14:29:20,921   274ms Terminals              Main               - Start state 7 Complete: Initilizing Persistence
INFO  2019-04-10 14:29:20,923   276ms Terminals              Main               - Start state 8 Complete: Configuration upgrade
INFO  2019-04-10 14:29:20,924   277ms Terminals              TryLoadFile        - Loading History from: C:\Users\btreas\AppData\Local\Robert_Chartier\Terminals\Data\History.xml
ERROR 2019-04-10 14:29:25,034  4388ms Terminals              orPublishedRelease - Failed during Check for release.
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Terminals.Updates.UpdateManager.DownloadReleases()
   at Terminals.Updates.UpdateManager.DownLoadLatestReleaseInfo(Version currentVersion)
   at Terminals.Updates.UpdateManager.TryCheckForPublishedRelease(Version currentVersion)
   at Terminals.Updates.UpdateManager.CheckForPublishedRelease(Version currentVersion)
ERROR 2019-04-10 14:29:25,124  4478ms Terminals              Register           - Error accessing registry
System.UnauthorizedAccessException: Access to the registry key 'HKEY_CLASSES_ROOT\TRM' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at Terminals.ProtocolHandler.CreateTrmRegistrySubKey()
   at Terminals.ProtocolHandler.Register()
