### ISSUE TITLE
Empty path name is not legal when using ssh

### ISSUE THREAD

**Issue by sssavio** [Terminals-Origin/Terminals#213]
Hello,
it gives me that error when I try to connect using ssh to a server.

This is the log file:
ERROR 2019-06-10 17:27:14,512  1215ms Terminals              Register           - Error accessing registry
System.UnauthorizedAccessException: Access to the registry key 'HKEY_CLASSES_ROOT\TRM' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at Terminals.ProtocolHandler.CreateTrmRegistrySubKey()
   at Terminals.ProtocolHandler.Register()
ERROR 2019-06-10 17:27:15,068  1771ms Terminals              orPublishedRelease - Failed during Check for release.
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Terminals.Updates.UpdateManager.DownloadReleases()
   at Terminals.Updates.UpdateManager.DownLoadLatestReleaseInfo(Version currentVersion)
   at Terminals.Updates.UpdateManager.TryCheckForPublishedRelease(Version currentVersion)
   at Terminals.Updates.UpdateManager.CheckForPublishedRelease(Version currentVersion)
INFO  2019-06-10 17:27:16,996  3700ms Terminals              SaveHistory        - History saved. Duration:13 ms
INFO  2019-06-10 17:27:17,017  3720ms Terminals              Connect            - Connecting to a SSH Connection
FATAL 2019-06-10 17:27:17,171  3874ms Terminals              Connect            - Connecting to unknown Connection
System.ArgumentException: Empty path name is not legal.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Granados.SSH2.SSH2Connection.UserAuth()
   at Granados.SSH2.SSH2Connection.Connect()
   at Granados.SSHConnection.ConnectMain(SSHConnectionParameter param, ISSHConnectionEventReceiver receiver, VersionExchangeHandler pnh, AbstractGranadosSocket s)
   at SSHClient.Protocol.Connect(Socket s)
   at Terminals.Connections.TerminalConnection.ConfigureSshConnection(IGuardedSecurity security)
   at Terminals.Connections.TerminalConnection.Connect()

**Comment by luiz-telles** [comment]
There is a workaroud here: https://github.com/Terminals-Origin/Terminals/issues/145
