### ISSUE TITLE
Corrupted Favourites Passwords

### ISSUE THREAD

**Issue by julianhall** [Terminals-Origin/Terminals#259]
Hi, I've been working on this for a few days now and am giving up, unless someone can help.

I attempted to open my terminals as normal, and was sent through the original setup screens all of a sudden.  

If I attempt to view the settings on a favourite with a saved password - i get the following
![image](https://user-images.githubusercontent.com/1324938/188884597-f9d66f42-118d-485e-8e51-449e807b9b53.png)

Looking at the logs: I can see the following:

`
INFO  2022-09-07 08:58:11,697   256ms Terminals              TryLoadFile        - Loading History from: D:\_dev\terminals\Data\History.xml
ERROR 2022-09-07 08:58:16,578  5137ms Terminals              DecryptPassword    - Error Decrypting Password
System.Exception: Error while writing encrypted data to the stream: 
Padding is invalid and cannot be removed.
   at Unified.Encryption.Decryptor.Decrypt(Byte[] bytesData, Byte[] bytesKey)
   at Terminals.Security.PasswordFunctions2.DecryptPassword(String encryptedPassword, Byte[] passwordKey)
   at Terminals.Security.PasswordFunctions2.DecryptPassword(String encryptedPassword, String keyMaterial)
`

I've attempted to replace the files in the Data folder with a backup of:
Favourites.xml
History.xml
Terminals.config
ToolStrip.settings.config

but still all my saved passwords are corrupted. 

ANY help on how to restore this would be greatly appreciated.

**Comment by ocpforme** [comment]
Got the exact same thing happening to me. The issue is with a Group Policy change that enabled FipsAlgorithmPolicy. I changed the 1 value in the registry to zero and it worked. [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy]
"Enabled"=dword:00000000

The log had the error:
ERROR 2022-10-07 10:33:24,438  8547ms Terminals              DecryptPassword    - Error Decrypting Password
System.InvalidOperationException: **This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.**

Searched for the error and found several tips about the registry fix. Tried it and it worked. Back in Business

**Comment by jirkapok** [comment]
This requires check of FIPS policy, Terminals is NOT FIPS compliant.
It needs research for possible solutions.

**Comment by roberto-ciccariello** [comment]
I have the same issue but in my case in the registry I already have this value set to 0 [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy]
"Enabled"=dword:00000000

Someone resolved in other ways?

Where do I find the log of Terminals?
