### ISSUE TITLE
Can't SSH to OpenWRT

### ISSUE THREAD

**Issue by zstomp** [Terminals-Origin/Terminals#32]
```
Granados.SSHException: The destination would not be a correct SSH server.
   at Granados.IO.SynchronizedDataHandler.Dequeue()
   at Granados.SSHConnection.ConnectMain(SSHConnectionParameter param, ISSHConnectionEventReceiver receiver, VersionExchangeHandler pnh, AbstractGranadosSocket s)
   at SSHClient.Protocol.Connect(Socket s)
   at Terminals.Connections.TerminalConnection.ConfigureSshConnection(IGuardedSecurity security)
   at Terminals.Connections.TerminalConnection.Connect()
```

**Comment by sinancetinkaya** [comment]
I have this problem too. I can't SSH to my OpenWRT router.
![image](https://user-images.githubusercontent.com/2675655/34366935-f1f8dc92-eab3-11e7-9720-c8e37d61fd69.png)

**Comment by jirkapok** [comment]
in next version ssh will be replaced by putty. Closing as want fix.
