### ISSUE TITLE
Can't export all connections

### ISSUE THREAD

**Issue by nexxai** [Terminals-Origin/Terminals#40]
If I click "Select all", the program immediately crashes.  If I manually select the sites one by one, it will let me choose the file location, and then crash.

Select all crash log:
```
INFO  2017-06-11 18:33:09,566   899ms Terminals              TryLoadFile        - Loading History from: C:\Users\jsmith\AppData\Local\Robert_Chartier\Terminals\Data\History.xml
FATAL 2017-06-11 18:33:21,877 13210ms Terminals              howApplicationExit - System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminals.Forms.Controls.FavoriteTreeNode.UpdateByFavorite(IFavorite favorite, String toolTip)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNode(IFavorite favorite, Int32 index)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNodes(IEnumerable`1 favorites)
   at Terminals.Forms.Controls.FavoriteTreeListLoader.LoadGroupNodesRecursive(TreeListNodes nodes)
   at Terminals.Forms.ExportForm.BtnSelect_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
FATAL 2017-06-11 18:33:21,893 13226ms Terminals              howApplicationExit - Application has to be terminated.
```

Manually selecting crash log:
```
INFO  2017-06-11 18:34:54,643   916ms Terminals              TryLoadFile        - Loading History from: C:\Users\jsmith\AppData\Local\Robert_Chartier\Terminals\Data\History.xml
FATAL 2017-06-11 18:35:19,193 25466ms Terminals              howApplicationExit - System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminals.Forms.Controls.FavoriteTreeNode.UpdateByFavorite(IFavorite favorite, String toolTip)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNode(IFavorite favorite, Int32 index)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNodes(IEnumerable`1 favorites)
   at Terminals.Forms.Controls.FavoriteTreeListLoader.OnTreeViewExpand(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterExpand(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnExpanded(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
FATAL 2017-06-11 18:35:19,197 25470ms Terminals              howApplicationExit - Application has to be terminated.
```

Any thoughts as to what might be causing this?

**Comment by stractenberg-sps** [comment]
Also having the same problem.

**Comment by Amethi** [comment]
Same here.

**Comment by jirkapok** [comment]
Duplicates #1 .
