### ISSUE TITLE
Terminals 4.0.0 crashes on File > Export connections

### ISSUE THREAD

**Issue by nealrout** [Terminals-Origin/Terminals#42]
I can no longer export my connections as the application crashes when I attempt to.  Below are the contents of log file:

INFO  2017-06-16 11:12:44,875   273ms Terminals              Main               - -------------------------------Title: Terminals 4.0.0 started Version:4.0.0.41829 Date:4/1/2017 7:14:19 PM-------------------------------
INFO  2017-06-16 11:12:44,945   343ms Terminals              Main               - Start state 1 Complete: Unhandled exceptions
INFO  2017-06-16 11:12:44,949   347ms Terminals              gGeneralProperties - CommandLine:"C:\Program Files (x86)\Terminals\Terminals.exe" 
INFO  2017-06-16 11:12:44,950   348ms Terminals              gGeneralProperties - CurrentDirectory:C:\Program Files (x86)\Terminals
INFO  2017-06-16 11:12:44,951   349ms Terminals              gGeneralProperties - MachineName:G2UA6192GLDE
INFO  2017-06-16 11:12:44,952   350ms Terminals              gGeneralProperties - OSVersion:Microsoft Windows NT 6.1.7601 Service Pack 1
INFO  2017-06-16 11:12:44,952   350ms Terminals              gGeneralProperties - ProcessorCount:16
INFO  2017-06-16 11:12:44,953   351ms Terminals              gGeneralProperties - UserInteractive:True
INFO  2017-06-16 11:12:44,954   352ms Terminals              gGeneralProperties - Version:4.0.30319.42000
INFO  2017-06-16 11:12:44,954   352ms Terminals              gGeneralProperties - WorkingSet:34598912
INFO  2017-06-16 11:12:44,955   353ms Terminals              gGeneralProperties - Is64BitOperatingSystem:True
INFO  2017-06-16 11:12:44,956   354ms Terminals              gGeneralProperties - Is64BitProcess:True
INFO  2017-06-16 11:12:44,956   354ms Terminals              Main               - Start state 2 Complete: Log General properties
INFO  2017-06-16 11:12:44,959   357ms Terminals              Main               - Start state 3 Complete: Set application properties
INFO  2017-06-16 11:12:45,048   446ms Terminals              Main               - Start state 4 Complete: Parse command line
INFO  2017-06-16 11:12:45,051   449ms Terminals              Main               - Start state 5 Complete: User account control
INFO  2017-06-16 11:12:45,052   450ms Terminals              Main               - Start state 6 Complete: Set Single instance mode
INFO  2017-06-16 11:12:45,249   647ms Terminals              Main               - Start state 7 Complete: Initilizing Persistence
INFO  2017-06-16 11:12:45,252   650ms Terminals              Main               - Start state 8 Complete: Configuration upgrade
INFO  2017-06-16 11:12:45,255   653ms Terminals              TryLoadFile        - Loading History from: C:\Users\asdfasdf\AppData\Local\Robert_Chartier\Terminals\Data\History.xml
FATAL 2017-06-16 11:13:11,578 26975ms Terminals              howApplicationExit - System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminals.Forms.Controls.FavoriteTreeNode.UpdateByFavorite(IFavorite favorite, String toolTip)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNode(IFavorite favorite, Int32 index)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNodes(IEnumerable`1 favorites)
   at Terminals.Forms.ExportForm..ctor(IPersistence persistence, ConnectionManager connectionManager, FavoriteIcons favoriteIcons)
   at Terminals.MainForm.ExportConnectionsListToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
FATAL 2017-06-16 11:13:11,582 26979ms Terminals              howApplicationExit - Application has to be terminated.

**Comment by HubertusKolster** [comment]
My Version 4.0.0 crashes if I try to export my connections. 
Windows 7 Prof

**Comment by jirkapok** [comment]
Duplicates #1
