### ISSUE TITLE
SSH: IndexOutOfRangeException exception when copying multi-line text

### ISSUE THREAD

**Issue by RossPatterson** [Terminals-Origin/Terminals#48]
This was [issue #43208 on CodePlex](http://terminals.codeplex.com/workitem/43208), but I just had it happen using version 4.0.0 a couple of days ago, so it hasn't been resolved yet.

When you have a SSH connection open and select some text that spans the end of a screen row, Terminals will crash.  This only happens when you're highlighting more than a single line, or a line so long it wraps around in the window.

I'm pretty sure this is a bug in `WalburySoftware.TerminalEmulator.CopySelectedText()`. There is a loop that attempts to figure out where the selected text ends, in the specific case of a select to end-of-line. (see lines 687-694 of `/Source/TerminalEmulator/TerminalControl.cs` as of commit #fa735e4). It looks to me like the loop should stop the first time it finds a '\0', but in fact it continues counting columns to the end of the row.

The log shows:

```
INFO  2017-06-23 10:00:52,279 50818ms Terminals              Connect            - Connecting to a SSH Connection
FATAL 2017-06-23 10:02:23,451 141990ms Terminals              howApplicationExit - System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WalburySoftware.TerminalEmulator.ScreenScrape(Int32 StartRow, Int32 StartColumn, Int32 EndRow, Int32 EndColumn)
   at WalburySoftware.TerminalEmulator.CopySelectedText()
   at WalburySoftware.TerminalEmulator.OnMouseUp(MouseEventArgs CurArgs)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at WalburySoftware.TerminalEmulator.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
FATAL 2017-06-23 10:02:23,457 141996ms Terminals              howApplicationExit - Application has to be terminated.
```

The failing loop is as follows, and it's failing at the "// we found the end" line:

```
for (col = 0; col < this._cols; col++) // parse the row
{
    if (this.CharGrid[row][col] == '\0') // we found the end
    {
        stop.X = col - 1;
        stop.Y = row;
    }
}
```

**Comment by jirkapok** [comment]
Please provide pull request, if you see it as relevant yet. Because focus of version under active development is Putty integration, the Control it self is going to be replaced.
