### ISSUE TITLE
Error when exporting the connections

### ISSUE THREAD

**Issue by edgardojimenez** [Terminals-Origin/Terminals#49]
I have a terminal instance with many groups/connections, and every time I try to export the connections if fails.  I get the popup that states: "Terminals has encountered a problem and needs to close.  for more details see logs files".   The log files contains:

FATAL 2017-06-27 12:29:04,772 2230028ms Terminals              howApplicationExit - System.NullReferenceException: Object reference not set to an instance of an object.
   at Terminals.Forms.Controls.FavoriteTreeNode.UpdateByFavorite(IFavorite favorite, String toolTip)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNode(IFavorite favorite, Int32 index)
   at Terminals.Forms.Controls.TreeListNodes.AddFavoriteNodes(IEnumerable`1 favorites)
   at Terminals.Forms.ExportForm..ctor(IPersistence persistence, ConnectionManager connectionManager, FavoriteIcons favoriteIcons)
   at Terminals.MainForm.ExportConnectionsListToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
FATAL 2017-06-27 12:29:04,777 2230034ms Terminals              howApplicationExit - Application has to be terminated.

This is happening in a Windows 10 64bit and on a Windows Server 2008 R2 64bit

Let me know if you have any other questions.

Thanks

**Comment by jirkapok** [comment]
Did you upgrade to latest version 4.0.1, should be fixed?

**Comment by edgardojimenez** [comment]
I just did and that worked.  Thanks

**Comment by TomHazlett** [comment]
Hi

When I upgrade (4.0.0 to 4.0.1) will my existing saved connections be included in the upgrade or will they be lost - this was why I trying to export them before upgrading (I have a LOT and don't wish to spend half a day rebuilding it) ?

Best regards
Tom

**Comment by TomHazlett** [comment]
I found a favourites.xml file in my user settings that I saved in case the upgrade went west, it didn't so I can agree that 4.0.0 to 4.0.1 upgrade does not lose any settings (phew).

**Comment by jirkapok** [comment]
Backup whole Data directory is the solution, also credentials are stored in the same place.

**Comment by TomHazlett** [comment]
Thanks for the confirmation, best regards.
