### ISSUE TITLE
Using SSH or Telnet cause crash.

### ISSUE THREAD

**Issue by eskes1** [Terminals-Origin/Terminals#6]
Using SSH or Telnet cause crash.
Create a SSH or telnet connection. Click on it it and you get a error then crash with ssh.
With telent you get a crash and telnet entry are gone.
Using database store.
I think it might be a error in path.

"A error occerred certing the coonfigarutin section handelsr for SSH;"
The system can't find the file " c:\user\USERNAME\Appdata\Local\Robert_Chartier\Terminlas\Data\terminals.config"

**Comment by kendoori** [comment]
I am having the same issue. I can SSH via putty to my server, but Terminals crashes with this error

![image](https://cloud.githubusercontent.com/assets/2447420/25198308/0f538d24-2515-11e7-9a89-3bc8a45a4576.png)

**Comment by Shadow00Caster** [comment]
When trying to create an SSH favorite I crash on latest 4.0.1.  Using portable setup with file store password protected.

`FATAL 2017-09-03 12:09:31,442 11164ms Terminals              howApplicationExit - System.MissingMethodException: Method not found: 'Void SSHClient.Preferences.set_AuthMethod(Terminals.Common.Configuration.AuthMethod)'.
   at Terminals.Forms.EditFavorite.SshControl.InitializeComponent()
   at Terminals.Connections.Terminal.SshConnectionPlugin.CreateOptionsControls()
   at Terminals.Forms.EditFavorite.FavoritePropertiesControl.GenearalPanel1ProtocolChanged(String newProtocol)
   at Terminals.Forms.EditFavorite.GeneralPropertiesUserControl.FireProtocolChanged()
   at Terminals.Forms.EditFavorite.GeneralPropertiesUserControl.ProtocolComboBox_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
FATAL 2017-09-03 12:09:31,444 11165ms Terminals              howApplicationExit - Application has to be terminated.`
