### ISSUE TITLE
SSH connection not working in v4.0.1

### ISSUE THREAD

**Issue by jlanzarotta** [Terminals-Origin/Terminals#76]
I am having an issue with v4.0.1 and an SSH connection.  When I attempt to connect I get:

```
Sorry, Terminals was unable to connect to the remote machine.  Try again, or check the log for more information.

Details:
Object reference not set to an instance of an object.
```
The log file looks like this:

```
FATAL 2017-08-16 09:15:11,408 52718ms Terminals              Connect            - Connecting to unknown Connection
System.NullReferenceException: Object reference not set to an instance of an object.
   at SSHClient.Protocol.Connect(Socket s)
   at Terminals.Connections.TerminalConnection.ConfigureSshConnection(IGuardedSecurity security)
   at Terminals.Connections.TerminalConnection.Connect()
```

My SSH connection is using "Password".

Any ideas?

**Comment by Pafzedog** [comment]
Same Version, same problem

**Comment by kentzjh** [comment]
You need to create a ssh key at first

**Comment by unficyp** [comment]
same problem here - connection is set to password, generating ssh key doesnt change anything - and why do i need a ssh key when the hosts doesnt support that and is set to password and i dont want to save the password ?

**Comment by aswzen** [comment]
Same problem here..

**Comment by peera1** [comment]
I had the same issue , resolved it like this : 
1. set your username & pass 
2. Change SSH options to "Password"
![image](https://user-images.githubusercontent.com/51166216/181429133-c2f0ed89-af4e-40e8-9159-70ecb81a346b.png)
