### ISSUE TITLE
Zip Version Crash

### ISSUE THREAD

**Issue by mxmissile** [Terminals-Origin/Terminals#89]
unzip contents of the zip file into a folder,
execute terminals.exe
crashes

log:
```
INFO  2017-09-12 08:01:33,359    82ms Terminals              Main               - -------------------------------Title: Terminals 4.0.1 started Version:4.0.1.16210 Date:6/24/2017 3:00:22 AM-------------------------------
INFO  2017-09-12 08:01:33,383   106ms Terminals              Main               - Start state 1 Complete: Unhandled exceptions
INFO  2017-09-12 08:01:33,384   107ms Terminals              gGeneralProperties - CommandLine:"C:\Users\travish\Desktop\Apps\Terminals2\Terminals.exe" 
INFO  2017-09-12 08:01:33,385   108ms Terminals              gGeneralProperties - CurrentDirectory:C:\Users\travish\Desktop\Apps\Terminals2
INFO  2017-09-12 08:01:33,386   109ms Terminals              gGeneralProperties - MachineName:TANK
INFO  2017-09-12 08:01:33,386   109ms Terminals              gGeneralProperties - OSVersion:Microsoft Windows NT 6.2.9200.0
INFO  2017-09-12 08:01:33,386   109ms Terminals              gGeneralProperties - ProcessorCount:8
INFO  2017-09-12 08:01:33,386   109ms Terminals              gGeneralProperties - UserInteractive:True
INFO  2017-09-12 08:01:33,386   109ms Terminals              gGeneralProperties - Version:4.0.30319.42000
INFO  2017-09-12 08:01:33,386   109ms Terminals              gGeneralProperties - WorkingSet:23367680
INFO  2017-09-12 08:01:33,387   110ms Terminals              gGeneralProperties - Is64BitOperatingSystem:True
INFO  2017-09-12 08:01:33,387   110ms Terminals              gGeneralProperties - Is64BitProcess:True
INFO  2017-09-12 08:01:33,387   110ms Terminals              Main               - Start state 2 Complete: Log General properties
INFO  2017-09-12 08:01:33,387   110ms Terminals              Main               - Start state 3 Complete: Set application properties
INFO  2017-09-12 08:01:33,427   150ms Terminals              Main               - Start state 4 Complete: Parse command line
INFO  2017-09-12 08:01:33,428   151ms Terminals              Main               - Start state 5 Complete: User account control
INFO  2017-09-12 08:01:33,428   151ms Terminals              Main               - Start state 6 Complete: Set Single instance mode
ERROR 2017-09-12 08:01:33,432   156ms Terminals              oadAssemblyPlugins - Unable to load plugins from 'C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Ica\Terminals.Plugins.Ica.dll'.
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Ica\Terminals.Plugins.Ica.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Ica\Terminals.Plugins.Ica.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Terminals.Connections.PluginsLoader.LoadAssemblyPlugins(String pluginFile)


ERROR 2017-09-12 08:01:33,437   160ms Terminals              oadAssemblyPlugins - Unable to load plugins from 'C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Rdp\Terminals.Plugins.Rdp.dll'.
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Rdp\Terminals.Plugins.Rdp.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Rdp\Terminals.Plugins.Rdp.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Terminals.Connections.PluginsLoader.LoadAssemblyPlugins(String pluginFile)


ERROR 2017-09-12 08:01:33,438   162ms Terminals              oadAssemblyPlugins - Unable to load plugins from 'C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Terminal\Terminals.Plugins.Terminal.dll'.
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Terminal\Terminals.Plugins.Terminal.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Terminal\Terminals.Plugins.Terminal.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Terminals.Connections.PluginsLoader.LoadAssemblyPlugins(String pluginFile)


ERROR 2017-09-12 08:01:33,440   163ms Terminals              oadAssemblyPlugins - Unable to load plugins from 'C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Vmrc\Terminals.Plugins.Vmrc.dll'.
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Vmrc\Terminals.Plugins.Vmrc.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Vmrc\Terminals.Plugins.Vmrc.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Terminals.Connections.PluginsLoader.LoadAssemblyPlugins(String pluginFile)


ERROR 2017-09-12 08:01:33,441   164ms Terminals              oadAssemblyPlugins - Unable to load plugins from 'C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Vnc\Terminals.Plugins.Vnc.dll'.
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Vnc\Terminals.Plugins.Vnc.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Vnc\Terminals.Plugins.Vnc.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Terminals.Connections.PluginsLoader.LoadAssemblyPlugins(String pluginFile)


ERROR 2017-09-12 08:01:33,442   165ms Terminals              oadAssemblyPlugins - Unable to load plugins from 'C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Web\Terminals.Plugins.Web.dll'.
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Web\Terminals.Plugins.Web.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Users\travish\Desktop\Apps\Terminals2\Plugins\Web\Terminals.Plugins.Web.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Terminals.Connections.PluginsLoader.LoadAssemblyPlugins(String pluginFile)


FATAL 2017-09-12 08:01:33,443   166ms Terminals              howApplicationExit - System.ApplicationException: No available protocol plugin was loaded.
   at Terminals.Connections.PluginsLoader.Load()
   at Terminals.Connections.ConnectionManager..ctor(IPluginsLoader loader)
   at Terminals.Program.Main()
FATAL 2017-09-12 08:01:33,443   166ms Terminals              howApplicationExit - Application has to be terminated.
```

**Comment by mxmissile** [comment]
Adding this to terminals.exe.config fixed it:

```
<runtime>
      <loadFromRemoteSources enabled="true"/>
</runtime>
```

**Comment by kennethahoward** [comment]
Where did you add that node to fix it?

**Comment by mxmissile** [comment]
@kennethahoward just in the `configuration` node, updated my comment

**Comment by leonel7** [comment]
@mxmissile it works! thanks for the fix!

**Comment by amatesi** [comment]
Looks like this issue is back (for me at least..).

My terminals.exe.config as follows:
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
    **<runtime>
        <loadFromRemoteSources enabled="true"/>
    </runtime>**
  <configSections>
    <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
      <section name="Terminals.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
    </sectionGroup>
    <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
      <section name="Terminals.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
    </sectionGroup>
    
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0" />
  </startup>
  <userSettings>
    <Terminals.Properties.Settings>
      <setting name="Initializer" serializeAs="String">
        <value />
      </setting>
    </Terminals.Properties.Settings>
  </userSettings>
  <applicationSettings>
    <Terminals.Properties.Settings>
      <setting name="Portable" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="ReleasesUrl" serializeAs="String">
        <value>https://api.github.com/repos/Terminals-Origin/Terminals/releases</value>
      </setting>
    </Terminals.Properties.Settings>
  </applicationSettings>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlConnectionFactory, EntityFramework" />
  </entityFramework>
</configuration>`

I keep getting:
`INFO  2019-10-22 09:28:41,092 65260353ms Terminals              SaveHistory        - History saved. Duration:8 ms
INFO  2019-10-22 09:43:39,796 66159057ms Terminals              SaveHistory        - History saved. Duration:5 ms
INFO  2019-10-22 09:44:42,633 66221894ms Terminals              Main               - -------------------------------Terminals 4.0.1 Stopped-------------------------------
INFO  2019-10-22 10:26:35,840   338ms Terminals              Main               - -------------------------------Title: Terminals 4.0.1 started Version:4.0.1.16210 Date:24/06/2017 6:00:22 PM-------------------------------
INFO  2019-10-22 10:26:35,962   460ms Terminals              Main               - Start state 1 Complete: Unhandled exceptions
INFO  2019-10-22 10:26:35,964   462ms Terminals              gGeneralProperties - CommandLine:"C:\Terminals\Terminals.exe" 
INFO  2019-10-22 10:26:35,964   462ms Terminals              gGeneralProperties - CurrentDirectory:C:\Terminals
INFO  2019-10-22 10:26:35,964   462ms Terminals              gGeneralProperties - MachineName:ENEENB005
INFO  2019-10-22 10:26:35,965   463ms Terminals              gGeneralProperties - OSVersion:Microsoft Windows NT 6.2.9200.0
INFO  2019-10-22 10:26:35,965   463ms Terminals              gGeneralProperties - ProcessorCount:8
INFO  2019-10-22 10:26:35,965   463ms Terminals              gGeneralProperties - UserInteractive:True
INFO  2019-10-22 10:26:35,966   464ms Terminals              gGeneralProperties - Version:4.0.30319.42000
INFO  2019-10-22 10:26:35,966   464ms Terminals              gGeneralProperties - WorkingSet:26398720
INFO  2019-10-22 10:26:35,966   464ms Terminals              gGeneralProperties - Is64BitOperatingSystem:True
INFO  2019-10-22 10:26:35,967   465ms Terminals              gGeneralProperties - Is64BitProcess:True
INFO  2019-10-22 10:26:35,967   465ms Terminals              Main               - Start state 2 Complete: Log General properties
INFO  2019-10-22 10:26:36,656  1154ms Terminals              Main               - Start state 3 Complete: Set application properties
INFO  2019-10-22 10:26:36,824  1322ms Terminals              Main               - Start state 4 Complete: Parse command line
INFO  2019-10-22 10:26:36,826  1324ms Terminals              Main               - Start state 5 Complete: User account control
INFO  2019-10-22 10:26:36,826  1324ms Terminals              Main               - Start state 6 Complete: Set Single instance mode
ERROR 2019-10-22 10:26:36,866  1363ms Terminals              oadAssemblyPlugins - Unable to load plugins from 'C:\Terminals\Plugins\Ica\Terminals.Plugins.Ica.dll'.
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Terminals\Plugins\Ica\Terminals.Plugins.Ica.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Terminals\Plugins\Ica\Terminals.Plugins.Ica.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Terminals.Connections.PluginsLoader.LoadAssemblyPlugins(String pluginFile)`

**Comment by LeslieDesser** [comment]
For me, adding

    <runtime>
        <loadFromRemoteSources enabled="true"/>
    </runtime>

before the final '</configuration>' worked.  Some other attempts failed.

**Comment by robhurt** [comment]
To be explicit - the file to modify is Terminals.exe.config and it is located in the same folder as the Terminals.exe

The entry to resolve the issue is located here after the close of entityFramework
  </entityFramework>
    <runtime>
        <loadFromRemoteSources enabled="true"/>
    </runtime>  
</configuration>

**Comment by robhurt** [comment]
`  </entityFramework>
    <runtime>
        <loadFromRemoteSources enabled="true"/>
    </runtime>  
</configuration>`

**Comment by SetiGeek** [comment]
Issue still present in Release 4.0.1
If I unzip the archive with Windows zip (right-click, extract), I have the problem (same log as reported in the OP).
Whereas if I extract the archive with 7Zip, I don't have the problem.
I do a filehash on the extracted file, but both are same (wrong.csv is the files extracted by Windows utility, correct.csv is the files extracted by 7zip). As you can see, no difference.
[correct.csv](https://github.com/Terminals-Origin/Terminals/files/9574705/correct.csv)
[wrong.csv](https://github.com/Terminals-Origin/Terminals/files/9574706/wrong.csv)

**Comment by RickkeeC** [comment]
Using 7Zip worked for me too, without adding the extra lines <grin>  We'll take it for a ride.
